@startmindmap
* begin
** English
*** Chart Composition
**** 2011
***** 2011【英二】.md
***** 3478E3211CF3C925AC4870CCF81BFD32.png
**** 2013
***** 2013【英语二】.md
***** Direction.jpg
**** 2014
***** 2014.md
***** 2014Chart.png
**** 2015
***** 2015【英语二】.md
***** Direction.png
**** 2017
***** 2017-Direction.png
***** 2017-英语二.md
**** 2019
***** 2019-Direction.png
***** 2019-英语二.md
*** Practical Writing
**** Advocay letter.md
**** Apologies.md
**** Congratulation and Suggestions.md
**** Gratitude and Suggestions.md
**** Invitation.md
**** Notice.md
**** Recommendations.md
**** Reply.md
**** Suggestions.md
*** 启承转合.md
** Politics
*** 中国近现代史纲要.md
*** 思想道德修养和法律基础.md
*** 毛泽东思想和中国特色社会主义理论体系概论.md
*** 考点背诵.md
*** 马克思主义基本原理概论.md
** Professional course
*** 中断体系.png
*** 操作系统.md
*** 计算机网络.md
*** 计算机网络专用术语.md
*** 错题集.md
@endmindmap